title: My Portfolio
description: This is my portfolio website
baseurl: "" # Leave empty for GitHub Pages
url: "https://marekhoffreiter.github.io"
theme: jekyll-theme-cayman # Or any other Jekyll theme you're using
